---
driver:
  name: default
platforms:
  - name: molecule-test-instance
provisioner:
  name: ansible
  inventory:
    host_vars:
      molecule-test-instance:
        ansible_connection: community.general.incus
        ansible_user: root
        ansible_incus_project: default
  config_options:
    defaults:
      gathering: explicit
      roles_path: ${MOLECULE_PROJECT_DIRECTORY}/..
verifier:
  name: ansible
