---
galaxy_info:
  role_name: incus_snapshots
  author: AnKLuMe
  description: Manage Incus instance snapshots (create, restore, delete, list)
  license: Apache-2.0
  min_ansible_version: "2.16"
  platforms:
    - name: Debian
      versions:
        - bookworm
        - trixie
    - name: ArchLinux
      versions:
        - all
dependencies: []
