---
galaxy_info:
  role_name: dev_agent_runner
  description: "Setup Claude Code Agent Teams runner container"
  company: AnKLuMe
  min_ansible_version: "2.16"
  platforms:
    - name: Debian
      versions:
        - trixie
  galaxy_tags:
    - development
    - testing
    - claude
dependencies: []
