---
galaxy_info:
  role_name: stt_server
  author: AnKLuMe
  description: "Install faster-whisper + Speaches STT server"
  license: Apache-2.0
  company: AnKLuMe
  min_ansible_version: "2.16"
  platforms:
    - name: Debian
      versions:
        - trixie
  galaxy_tags:
    - stt
    - whisper
    - speech
dependencies: []
