---
galaxy_info:
  role_name: base_system
  namespace: anklume
  author: AnKLuMe
  description: Base provisioning for all instances (packages, locale, timezone)
  license: Apache-2.0
  min_ansible_version: "2.16"
  platforms:
    - name: Debian
      versions:
        - bookworm
        - trixie
    - name: ArchLinux
      versions:
        - all
dependencies: []
