---
galaxy_info:
  role_name: incus_instances
  namespace: anklume
  author: anklume
  description: Reconcile Incus containers and VMs
  license: AGPL-3.0
  min_ansible_version: "2.16"
  platforms:
    - name: Debian
      versions:
        - bookworm
        - trixie
    - name: ArchLinux
      versions:
        - all
dependencies: []
