---
galaxy_info:
  role_name: dev_test_runner
  namespace: anklume
  author: AnKLuMe
  description: Provisions a container for nested Incus usage (Incus-in-Incus)
  license: Apache-2.0
  min_ansible_version: "2.16"
  platforms:
    - name: Debian
      versions:
        - trixie
dependencies: []
