---
galaxy_info:
  author: anklume
  description: Configure a firewall VM as inter-domain router
  license: AGPL-3.0
  min_ansible_version: "2.16"
  namespace: anklume
  role_name: firewall_router
dependencies: []
